### ISSUE TITLE
Can I ask you something?

### ISSUE THREAD

**Issue by Wangsujeon** [andmon97/FuzzyRemoteSensingSegmentation#1]
I saw the remote image segmentation code using fuzzy(ANFIS) on your github.
I'm trying to run your code on the gpu, but I get an error. What is the environment like? and I want to learn with the data I have. How do I create a csv file?

Thank you for answering the questions.

**Comment by andmon97** [comment]
Hi, sorry for the delay in responding.
I remember running the code on colab without problems, or on my computer installing requiremnts and using python 3.4 (if I remember correctly).

Regarding the csv file to create, if you want to use the same classification method (at the pixel level) you have to extract for each pixel of your photos, respectively the values of the r, g and b channels and the value of the entropy filter.
To get an example of the csv file I used for my experiments, in the repository go to FuzzyRemoteSensingSegmentation/preprocessing/WHDLD/reducedTC.csv

If you need further clarification I am available. Excuse me if I am not very precise. :(
